### ISSUE TITLE
build fails on Device::HID::XS dependency

### ISSUE THREAD

**Issue by draylang** [athreef/Device-HID#2]
in .004 you removed AutoPrereqs in dist.ini to resolve an external dependency issue with Device::HID::XS. AutoPrereqs was added back in .005.

Version .004 builds/installs for me while .005 does not. Perl 5.24.3 on Mac OSX.

Perhaps a skip line for AutoPrereqs in dist.ini would resolve this?

**Comment by a3f** [comment]
Oh, I must be mistunderstanding what `[AutoPrereqs / TestRequires] ` means. I thought that means use `AutoPrereqs` only for tests... v0.006 should be available shortly on CPAN that fixes the issue (by just removing the `AutoPrereqs` again).

Thanks for your report. Before my Steam controller dongle broke, I used `Device::HID` on macOS too and it worked, so if there's any fruther issue, please tell. :)

**Comment by draylang** [comment]
that may not be the best fix after all. I checked cpan testers and it is passing for all tested there.
I'm using Carton which is essentially the same as 'cpanm -v Device::HID --save-dists ./local/cache -L ./local'.

I just built to the default lib locations with no issues so let me research more. Your comment in the change logs made me think of that first.
